### PR TITLE
Switch tests from SimpleStrategy to NetworkTopologyStrategy

### PR DESCRIPTION
**Pull request by sylwiaszunejko**
SimpleStrategy is getting depricated, as replacement is it recomended to use NetworkTopologyStrategy instead. 

This PR switches tests to use NetworkTopologyStrategy. Tests that are specifically targeting SimpleStrategy stays as they are.

Fixes: #217

### CODE REVIEW

**Review by dkropachev — APPROVED** [review]

**Comment by dkropachev** [comment]
> I am not sure about the recreate tests, I only change the strategy in testdata/recreate files and used `updateGolden` option to automatically update golden files but the changes does not seem right https://github.com/scylladb/gocql/blob/master/recreate_test.go#L21 @dkropachev could you look at it? You added this option, maybe there is something I am missing on that part

Why you think these changes are wrong ? Sure, there are some difference, but it looks reasonable considering difference between scylla and cassandra implementations.

**Comment by sylwiaszunejko** [comment]
@dkropachev have you looked on these *_golden.cql files? There are a lot of changes there I not sure about

**Comment by sylwiaszunejko** [comment]
For example lack of `'replication_factor': '2'` in keyspace_golden.cql was something I was not sure about, but I guess `'datacenter1': '2'` means that in this dc replication factor is 2, I just wasn't that familiar with this notation

**Comment by dkropachev** [comment]
> For example lack of `'replication_factor': '2'` in keyspace_golden.cql was something I was not sure about, but I guess `'datacenter1': '2'` means that in this dc replication factor is 2, I just wasn't that familiar with this notation

Yes, it is also caught my attention, it should not happen, but it is happening not only for recreate tests.
It looks like a bug, we need to dig deeper into it.
Other than that I don't see any other problem there.

Since this potential bug has nothing to do with this PR, I think we can merge this PR and investigate issue later, WDYT ?

**Comment by sylwiaszunejko** [comment]
> > For example lack of `'replication_factor': '2'` in keyspace_golden.cql was something I was not sure about, but I guess `'datacenter1': '2'` means that in this dc replication factor is 2, I just wasn't that familiar with this notation
> 
> Yes, it is also caught my attention, it should not happen, but it is happening not only for recreate tests. It looks like a bug, we need to dig deeper into it. Other than that I don't see any other problem there.
> 
> Since this potential bug has nothing to do with this PR, I think we can merge this PR and investigate issue later, WDYT ?

OK

**Pull request merged**
