### PR TITLE
Test changes in `advanced_ci` branch

### PR DESCRIPTION
**Pull request by sylwiaszunejko**
The purpose of this PR is to run CI with workflow file added in `advanced_ci` branch in the main repo as it uses `pull_request_target` and that's why the CI doesn't run new workflow file.

### CODE REVIEW

**Comment by dkropachev** [comment]
@sylwiaszunejko , failing due to the https://github.com/scylladb/scylla-cluster-tests/issues/8721.
Also you need to pass image name to the jenkins job

**Comment by sylwiaszunejko** [comment]
> Also you need to pass image name to the jenkins job

@dkropachev What do you mean? I pass `SCT_STRESS_IMAGE.scylla-bench=scylladb/gocql-extended-ci:scylla-bench-advanced_ci_test` in the `extra_environment_variables` parameter

**Comment by dkropachev** [comment]
> > Also you need to pass image name to the jenkins job
> 
> @dkropachev What do you mean? I pass `SCT_STRESS_IMAGE.scylla-bench=scylladb/gocql-extended-ci:scylla-bench-advanced_ci_test` in the `extra_environment_variables` parameter

Sorry, now I see it.
It is better to have commit I'd in the image name, to avoid possible caching problems.

Another question,  how do we clean these images up?

**Comment by sylwiaszunejko** [comment]
> Another question, how do we clean these images up?

We do not have a mechanism for that yet

**Comment by sylwiaszunejko** [comment]
> It is better to have commit I'd in the image name, to avoid possible caching problems.

But which commit if PR contains many of them? Maybe repo_name-branch_name would be good enough and then we have one image for one PR always, so we do not have that many images piling up

**Comment by dkropachev** [comment]
> > It is better to have commit I'd in the image name, to avoid possible caching problems.
> 
> But which commit if PR contains many of them? 

Of course last commit id.
> Maybe repo_name-branch_name would be good enough and then we have one image for one PR always, so we do not have that many images piling up

We still going to have them and still going to deal with them, these images are not going to go away by themselves.
In this regard there is no difference between having 1 image per branch or having 5 images per branch, you still need a code to handle them.

You also going to have opportunity to go back and run test with image from prior version of them PR, in rare cases could be handy.

**Comment by sylwiaszunejko** [comment]
> > > It is better to have commit I'd in the image name, to avoid possible caching problems.
> > 
> > 
> > But which commit if PR contains many of them?
> 
> Of course last commit id.
> 
> > Maybe repo_name-branch_name would be good enough and then we have one image for one PR always, so we do not have that many images piling up
> 
> We still going to have them and still going to deal with them, these images are not going to go away by themselves. In this regard there is no difference between having 1 image per branch or having 5 images per branch, you still need a code to handle them.
> 
> You also going to have opportunity to go back and run test with image from prior version of them PR, in rare cases could be handy.

OK, I pushed the change, and I am staring my work on an workflow that will periodically scan docker hub and remove old images

**Comment by sylwiaszunejko** [comment]
@dkropachev Could you look at it? The last two runs https://jenkins.scylladb.com/view/scylla-drivers/job/scylla-drivers/job/gocql/job/extended-ci/job/longevity-large-partition-asymmetric-cluster-3h-test/ were successful but one job in github action was canceled

**Pull request closed without merging**
