### PR TITLE
Fix checking if tablets should be used in scyllaConnPicker Pick

### PR DESCRIPTION
**Pull request by sylwiaszunejko**
Previously the check was always based on `p.conns[0]`, but there is a posibility that it is nil and it should be checked. The check should be based on not nil connection.

This PR introduces searching for first not nil connection and checking tablet-awareness based on this connection.

Fixes: https://github.com/scylladb/scylla-bench/issues/134.

### CODE REVIEW

**Comment by piodul** [comment]
> There is a big chance that this will fix https://github.com/scylladb/scylla-bench/issues/134.

I don't think it is impossible to reproduce the issue in a local environment. We should attempt doing it first and checking whether the fix works before considering to merge this.

It's fine if you want to propose a fix and get feedback even if it is not confirmed that it solves the problem, but this should be clearly stated for the reviewers (e.g. in the PR description or a comment).

**Comment by sylwiaszunejko** [comment]
@piodul I have a hard time reproducing it, I am running scylla-bench with high concurrency and use nodes with smp set to large number, but the crash does not happen. Maybe load is too small, I am not sure.

> We should attempt doing it first and checking whether the fix works before considering to merge this.

I agree that reproducing is important for checking if it is the fix for the issue, but regardless of whether this is the case, to use of `p.conns[0]` is incorrect and should be fixed, am I right?

**Comment by piodul** [comment]
> I agree that reproducing is important for checking if it is the fix for the issue, but regardless of whether this is the case, to use of `p.conns[0]` is incorrect and should be fixed, am I right?

@sylwiaszunejko The fact that the issue slipped past the tests in CI show that this area/behavior is not properly covered with automated tests. The connection pool is a bit complex piece of the driver, so at least a manual test which exercises this code path is a must in my opinion.

It's true that the fix looks correct at a first glance, but I'd like to have an additional confirmation that it works.

**Comment by sylwiaszunejko** [comment]
I managed to reproduce https://github.com/scylladb/scylla-bench/issues/134 in SCT run - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/sylwia.szunejko/job/longevity-large-partition-200k-pks-4days-gce-test/4/
After the fix from this PR it does not reproduce: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/sylwia.szunejko/job/longevity-large-partition-200k-pks-4days-gce-test/5/

**Review by piodul — APPROVED** [review]

**Review by roydahan — APPROVED** [review]
LGTM

**Comment by sylwiaszunejko** [comment]
@roydahan @avelanarius suggested that I should think about writing some automated tests, but it is not obvious how to write them, because the issue does not reproduce locally. I tried to add some sleeps to check if slowing down the process of creating a connection will help, but it didn't work. I'm not sure if it's possible to write any automatic integration tests in this case, unfortunately.

**Review by avelanarius — APPROVED** [review]

**Comment by avelanarius** [comment]
OK, so let's merge it the way it is now.

**Comment by roydahan** [comment]
> @roydahan @avelanarius suggested that I should think about writing some automated tests, but it is not obvious how to write them, because the issue does not reproduce locally. I tried to add some sleeps to check if slowing down the process of creating a connection will help, but it didn't work. I'm not sure if it's possible to write any automatic integration tests in this case, unfortunately.

We can try introduce an integration test that uses large number shards, but I think you wrote that it didn't help you to reproduce the issue.

**Pull request merged**
