### PR TITLE
fix(dealer): make net.Dialer not to bind to reuse ephimeral ports

### LINKED ISSUE #179: Connection can randomly fail with `address already in use`
### What version of ScyllaDB or Cassandra are you using?
ScyllaDB 5.1.8-0.20230319.c90807d29f30

### What version of ScyllaDB Gocql driver are you using?
v.1.7.1
v.1.14.0

### What version of Go are you using?
1.22

### What did you do?
1. Run one node on docker: `docker run -d --name scylla scylladb/scylla:5.1.8` 
2. Make your system reuse ephemeral ports:
```
sysctl -w net.ipv4.tcp_tw_reuse=1
```
3. Run following program:
```
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strings"
	"sync"

	"github.com/gocql/gocql"
)

func main() {
	hosts := flag.String("cluster", "", "")
	flag.Parse()

	cluster := gocql.NewCluster(strings.Split(*hosts, ",")...)
	cluster.Authenticator = gocql.PasswordAuthenticator{
		Username: "xxxx",
		Password: "xxxx",
	}

	log.Println("Successfully connected")
	wg := sync.WaitGroup{}
	for routine := range 10 {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for try := range 1000 {
				fmt.Println("Routine:", routine, "Try:", try)
				s, err := gocql.NewSession(*cluster)
				if err != nil {
					log.Fatalf("unable to connect session: %v", err)
				}
				err = s.Query("SELECT * FROM system_schema.keyspaces").Iter().Close()
				if err != nil {
					log.Fatalf("unable to execute query: %v", err)
					os.Exit(1)
				}
				s.Close()
			}
		}()
	}
	wg.Wait()
}
```

### What did you expect to see?
Successfully finish

### What did you see instead?
```
2024/05/29 00:09:37 gocql: unable to dial control conn 172.17.0.2:9042: dial tcp :0->172.17.0.2:9042: bind: address already in use
2024/05/29 00:09:37 unable to connect session: gocql: unable to create session: unable to connect to initial hosts: dial tcp :0->172.17.0.2:9042: bind: address already in use
```
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster please provide the following information

- output of `nodetool status`:
```
root@7a290a1fba9c:/# nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  172.17.0.2  14.07 MB   256          ?       f882f9d5-ff8c-4f1c-ae3c-f5a308576237  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
root@7a290a1fba9c:/# 
```
- output of `SELECT peer, rpc_address FROM system.peers`
```
cqlsh> SELECT peer, rpc_address FROM system.peers;

 peer | rpc_address
------+-------------

(0 rows)
cqlsh> 
```
- rebuild your application with the `gocql_debug` tag and post the output
[test.log.zip](https://github.com/scylladb/gocql/files/15478661/test.log.zip)

### PR DESCRIPTION
**Pull request by dkropachev**
`net.Dialer` makes golang runtime run `bind` if `LocalAddr` is not nil, even if address is `":0"`.
https://github.com/golang/go/blob/master/src/net/sock_posix.go#L109-L117

Calling `bind`, due to it's nature, marks obtained port as non-reusable, which limits number of possible connections/sessions.

It is inevitable for `share-aware` connections, since we need to pick the port, but for `none-shard-aware` connections it must be avoided.

Closes #179

### CODE REVIEW

**Review by sylwiaszunejko — APPROVED** [review]

**Comment by roydahan** [comment]
@sylwiaszunejko do we need another maintainer reviewing it?
If so, please get someone to review and merge.

Also, please make sure we have tests to detect such an issue (looks like we don't).

**Comment by sylwiaszunejko** [comment]
@avelanarius  Could you look at it to make sure I didn't miss anything?

**Comment by sylwiaszunejko** [comment]
@dkropachev I was wondering how to write a test for this, but I am not sure. I was trying to use the issue reproducer, but without `fmt.Println("Routine:", routine, "Try:", try)` the issue stopped reproducing and with it or with analogues logging statement there was a error like that: `testing.go:1465: race detected during execution of test`. Do you have any ideas how to minimize reproducer or how to test this change some other way?

**Comment by dkropachev** [comment]
> @dkropachev I was wondering how to write a test for this, but I am not sure. I was trying to use the issue reproducer, but without `fmt.Println("Routine:", routine, "Try:", try)` the issue stopped reproducing and with it or with analogues logging statement there was a error like that: `testing.go:1465: race detected during execution of test`. Do you have any ideas how to minimize reproducer or how to test this change some other way?

There is no good way of doing it.
We could have an interface with something like :
```
DialContext(ctx context.Context, network, addr string) (net.Conn, error)
DialContextWithPort(ctx context.Context, network, addr string, sport uint16) (net.Conn, error)
```
And then mock it on test, but realy, this test won't acheve anything.
To me better just not test it at all

**Comment by sylwiaszunejko** [comment]
@roydahan FYI

**Pull request merged**
