### PR TITLE
Simplify tokenAwareHostPolicy.Pick

### PR DESCRIPTION
**Pull request by dkropachev**
Main goal of this PR is to make `tokenAwareHostPolicy.Pick` code less convoluted.
But there are little functional changes:
### Start shuffling hosts obtained from tablets
Before this PR hosts from tablets are not being shuffled 
### Consider next hosts information source if current got 0 hosts
There are three host information sources: tablets, meta and tokenring, 
Before this PR if tables returned no hosts for given token, in certain cases code did not consider meta or tokenring.
And same for meta, it did not consider tokenring.
After this PR, it starts goes through tablets, meta and tokenring, if current host sources yield no hosts it proceed to next one.
### Removes unnecessary locks
There was locking done on `cowTabletList` at `t.tablets` to read tablets, but since `cowTabletList` solves parallel access issue through COW, it is not needed.

### CODE REVIEW

**Comment by mykaul** [comment]
What issues does it solve? A one-line description (at least) would be appreciated.

**Comment by dkropachev** [comment]
> What issues does it solve? A one-line description (at least) would be appreciated.

Added

**Comment by sylwiaszunejko** [comment]
> Before this PR hosts from are not being shuffled

from tokenring? There is a missing information in the commit message and PR description

**Comment by dkropachev** [comment]
> > Before this PR hosts from are not being shuffled
> 
> from tokenring? There is a missing information in the commit message and PR description

Thanks, updated, from tablets

**Review by sylwiaszunejko — APPROVED** [review]

**Pull request merged**
